# Generated by Django 5.2.8 on 2025-11-28 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_CreateModel_User_Profile'),
        ('shops', '0001_UserShop_Relationship_Added'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='shops.shop'),
        ),
    ]
