# Generated by Django 5.2.8 on 2025-11-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_UserShop_Relationship_Added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
