# Generated by Django 5.2.8 on 2025-11-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_CreateModel_OperatingHour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatinghour',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operatinghour',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
